# ==================================================================
# Project metadata
# ==================================================================
# Author: Alyssa Bédard
# License: MIT License
# GitHub: https://github.com/alyssabedard/Hanzi2Pinyin
#
# Anki addon that automatically converts Chinese characters (Hanzi)
# to ruby-annotated text with pinyin and zhuyin readings.
# ==================================================================
[project]
name = "Hanzi2Pinyin"
release = "2025.09.22"
description = "Anki addon that automatically converts Chinese characters (Hanzi) to ruby-annotated text with pinyin and zhuyin readings."
authors = ["Alyssa Bédard"]
license = "MIT"
homepage = "https://github.com/alyssabedard/Hanzi2Pinyin"

[project.github]
documentation = "https://github.com/alyssabedard/Hanzi2Pinyin"
repository = "https://github.com/alyssabedard/Hanzi2Pinyin"
issues = "https://github.com/alyssabedard/Hanzi2Pinyin/issues"
feature-requests = "https://github.com/alyssabedard/Hanzi2Pinyin/issues"
discussions = "https://github.com/alyssabedard/Hanzi2Pinyin/discussions"

[project.anki]
addon-id = "77106192"
min-version = "25.09"       # Oldest supported Anki version
max-version = "^25.09"        # Latest supported Anki version
tested-version = "25.09"     # Manually update this when tested
conflicts = []              # List of any conflicting addon IDs
#dependencies = []          # List of any required addon ID

[project.maintainers]
primary = "Alyssa Bédard"
contributors = [
    "",
    ""
]

